import Head from 'next/head'
import Script from 'next/script'
import Footer from "../containers/footer/Footer";
import Header from "../containers/header/Header";
import { fonts } from '../theme/theme';


export default function MyApp({ Component, pageProps }) {
  return (
    <>
    <Head>
      <title>OscarFdez</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css"></link>
    </Head>
    <Script id="fontawsome"
        src="https://kit.fontawesome.com/f2a6b74cca.js"
        crossorigin="anonymous"
      />
    <Header/>
      <Component {...pageProps} />
    <Footer/>
    <style jsx global>
        {`
          .contetn-section {
            min-height: calc(100vh - 231px) !important;
            font-family: ${fonts.base}
          }
        `}
      </style>
    </>

  )
}