import Head from 'next/head'
import Link from "next/link"
import Footer from '../containers/footer/Footer'
import Header from '../containers/header/Header'
import Main from '../containers/main/Main'

export default function Home() {
  return (
    <div>
      <Head>
        <title>OscarFdez</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma.min.css"></link>
      </Head>

        <Header/>
      <main className='container'>
        <Main/>
      </main>
        <Footer/>
    </div>
  )
}
